## 简介

In [2]:
import numpy as np
# 创建ndarray
score = np.array(
[[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])


[[80 89 86 67 79]
 [78 97 89 67 81]
 [90 94 78 67 74]
 [91 91 90 67 69]
 [76 87 75 67 86]
 [70 79 84 67 84]
 [94 92 93 67 64]
 [86 85 83 67 80]]


## ndarray和原生list对比

In [4]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
  a.append(random.random())
# 通过%time魔法⽅法, 查看当前⾏的代码运⾏⼀次所花费的时间
%time sum1=sum(a)
b=np.array(a)
%time sum2=np.sum(b)

CPU times: total: 250 ms
Wall time: 556 ms
CPU times: total: 46.9 ms
Wall time: 113 ms


## 基本属性

In [12]:
print(score.shape)
print(score.ndim)
print(score.size)
print(score.itemsize)
print(score.dtype)

(8, 5)
2
40
4
int32


## 数组生成

In [17]:
# ⽣成0和1的数组
ones = np.ones([2,2])
zeros = np.zeros([3,3])
print(ones)
print(zeros)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 从现有数组生成

In [20]:
a = np.array([[1,2,3],[4,5,6]])
# 从现有的数组当中创建
a1 = np.array(a) # 深拷贝
# 相当于索引的形式，并没有真正的创建⼀个新的
a2 = np.asarray(a) #浅拷贝
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## ⽣成固定范围的数组

In [21]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [22]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])